# Generated by Django 4.2.21 on 2025-05-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("link", models.URLField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("doc", "Document"),
                            ("link", "Web Link"),
                            ("note", "Note"),
                        ],
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
