# Generated by Django 4.2.21 on 2025-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0002_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
